name: Deploy to GCP Cloud Run

on:
  push:
    branches:
      - main  # Runs on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: tomaba

      - name: Ensure Correct Service Account is Used
        run: |
          gcloud auth list
          gcloud config set account github-actions-deployer@tomaba.iam.gserviceaccount.com
          gcloud auth list  # Verify change

      - name: Deploy to Cloud Run
        run: |
          gcloud builds submit --tag gcr.io/tomaba/tomaba
          gcloud run deploy tomaba-bot \
            --image gcr.io/tomaba/tomaba \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
